# Generated by Django 5.0 on 2023-12-21 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryupdaterequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='description',
        ),
    ]
