# Generated by Django 4.2.5 on 2024-01-30 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_inventoryitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
