# Generated by Django 5.2.6 on 2025-09-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventoryitem_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='recommended_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='warning_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
