# Generated by Django 5.2.6 on 2025-09-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0002_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('manager', 'Manager'), ('admin', 'Admin'), ('front desk', 'Front Desk'), ('housekeeping', 'Housekeeping'), ('maintenance', 'Maintenance')], default='employee', max_length=12),
        ),
    ]
